### ISSUE TITLE
Potential issue in `cartesian_product` function typing

### ISSUE THREAD

**Issue by versecafe** [gleam-community/maths#29]
@NicklasXYZ Not sure if this was intentional if not I can patch it but cartesian product is set as

```gleam
pub fn cartesian_product(
  xarr: List(a),
  yarr: List(a),
) -> List(#(a, a))
```

but there is no limit in the set opperation that should prevent it from being

```gleam
pub fn cartesian_product(
  xarr: List(a),
  yarr: List(b),
) -> List(#(a, b))
```
> where b can but is not required to be of type a

I know that the unreleased code is using Set instead of List but it should be the same.

**Comment by NicklasXYZ** [comment]
Hi, yes. It is not intentional. It is a mistake. Feel free to make a PR :)
